

import math
import random
import sys
import numpy as np
from types import SimpleNamespace
from pathlib import Path
from tqdm import tqdm
from datasets import load_dataset
from scipy.signal import resample
from scipy.io import wavfile
from cfg import SourceConfig, config
import cfg
import torch
from TTS.api import TTS
from src import write_sample
from src import generate_simple_phrase_set



class CoquiTTSConfig(SourceConfig):
    model: str
    language: str
    positive_samples: int # TODO: We are generating too much positive samples (a lot of them will repeat)
                          # we should generate positive sample for each phrase and for each speaker, no need to provide count here
    negative_samples: int # TODO: Negative samples should work the same way, except optional field
                          # max_negative_samples_per_speaker may be used to limit number of negative samples
                          # The tool should output counts for user to verify
    weight: float # Since we have different number of sample, we may want to do positive_weight and negative_weight
    speaker_weights: dict[str, float] | None


def generate(tts_config: CoquiTTSConfig):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    tts = TTS(tts_config.model).to(device)

    print("Speakers and their weights:")
    speaker_weights = tts_config.speaker_weights or {}
    speakers = [
        (s, speaker_weights.get(s, tts_config.weight))
        for s in tts.speakers
    ]
    for speaker, weight in speakers:
        print(f"  {speaker}: {weight}")
    speakers = [p for p in speakers if p[1] > 0.0]
    
    sample_rate = tts.synthesizer.output_sample_rate
    speaker_index = 0
    
    all_phrases = generate_simple_phrase_set(tts_config.positive_samples, tts_config.negative_samples)

    for phrase, is_positive, sample_index in tqdm(all_phrases, desc=tts_config.dir):
        speaker_name, weight = speakers[speaker_index]
        speaker_index = (speaker_index + 1) % len(speakers)
        wav = tts.tts(text=phrase, language=tts_config.language, speaker=speaker_name)
        wav = np.array(wav, dtype=np.float32)
        max_val = np.max(np.abs(wav))
        if max_val <= 1.0:
            pass # no need to normalize
        elif max_val <= 256.0:
            wav = wav / 256.0
        elif max_val <= 65536.0:
            wav = wav / 65536.0
        else:
            wav = wav / max_val
        output_name = (('positive' if is_positive else 'negative')
            + f"/{sample_index // 100:03d}/{sample_index:05d}-{speaker_name.replace(' ', '-')}")
        write_sample(tts_config, sample_rate, wav, output_name, [{
            "start": 0.0,
            "end": len(wav) / sample_rate,
            "phrase": phrase,
            "weight": weight,
        }])


if __name__ == "__main__":
    if len(sys.argv) < 2:
        for index, source in enumerate(config.sources):
            if source.type == 'coqui-tts':
                break
    else:
        index = int(sys.argv[1])        
    generate(config.sources[index])



# TODO: Implement
# https://github.com/idiap/coqui-ai-TTS
# https://coqui-tts.readthedocs.io/
#
# 1. Use pre-trained single voice models (if available)
# 2. Find and download library of different speeches 
# 3. Use voice cloning with multiple models
# 4. Use voice conversion with multiple models
#    - Source files generated by other methods
#    - Speaker files from downloaded library


# import torch
# from TTS.api import TTS

# # Get device
# device = "cuda" if torch.cuda.is_available() else "cpu"

# print(f"Using device: {device}")

# # List available 🐸TTS models
# print('\n'.join(TTS().list_models()))

# # Initialize TTS
# tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

# # List speakers
# print(tts.speakers)

# # Run TTS
# # ❗ XTTS supports both, but many models allow only one of the `speaker` and
# # `speaker_wav` arguments

# # TTS with list of amplitude values as output, clone the voice from `speaker_wav`
# wav = tts.tts(
#   text="Hello world!",
#   speaker_wav="my/cloning/audio.wav",
#   language="en"
# )

# # TTS to a file, use a preset speaker
# tts.tts_to_file(
#   text="Hello world!",
#   speaker="Craig Gutsy",
#   language="en",
#   file_path="output.wav"
# )