
# TODO: Implement
# https://github.com/idiap/coqui-ai-TTS
# https://coqui-tts.readthedocs.io/
#
# 1. Use pre-trained single voice models (if available)
# 2. Find and download library of different speeches 
# 3. Use voice cloning with multiple models
# 4. Use voice conversion with multiple models
#    - Source files generated by other methods
#    - Speaker files from downloaded library
